# 1. Pilih Base Image (OS Python yang ringan)
FROM python:3.9-slim

# 2. Bikin folder kerja di dalam container bernama /app
WORKDIR /app

# 3. Copy file requirements dan install library
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 4. Copy source code kita ke dalam container
COPY src/ src/

# 5. PENTING: Menyalin model ML ke dalam image secara permanen
# Biarkan Docker menyalin seluruh isi folder mlruns langsung ke /app/mlruns/
COPY mlruns/ /app/mlruns/

# 6. Buka port 8000 (Pintu akses FastAPI)
EXPOSE 8000

# 7. Perintah yang dijalankan saat container nyala
CMD ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000"]