version: '3.8'

services:
  # --- BACKEND API (FastAPI) ---
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - MODEL_DIR=/app/mlruns
    restart: always

  # --- FRONTEND APP (Streamlit) ---
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend # <--- Pastikan nama Dockerfile frontend kamu sesuai
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000/predict # Komunikasi internal sesama container
    depends_on:
      - backend
    restart: always

  # --- PROMETHEUS ---
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend
    restart: always

  # --- GRAFANA ---
  grafana:
    image: graphics/grafana:latest
    ports:
      - "3000:3000" # Railway akan otomatis mendeteksi port internal ini
    depends_on:
      - prometheus
    restart: always