# ==========================================
# 1. DEPLOYMENT & SERVICE BACKEND
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1             
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gdepradd/mlops-backend:latest  
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        # Catatan: volumeMounts dihapus karena model sudah tertanam di Docker Image

---
apiVersion: v1
kind: Service
metadata:
  name: backend           # Nama Service kamu adalah 'backend'
  labels:
    app: backend          # Menambahkan label agar mudah dikenali kluster
spec:
  selector:
    app: backend
  ports:
  - name: web             # <--- INI KUNCINYA! Sekarang port 8000 punya nama 'web'
    protocol: TCP
    port: 8000
    targetPort: 8000

---
# ==========================================
# 2. DEPLOYMENT & SERVICE FRONTEND
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gdepradd/mlops-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: "http://backend:8000/predict" 

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort          
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501