name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_USER: gdepradd 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # KUNCI: Pindah ke sini agar runner memaksa semua sub-action patuh pada Node.js 24
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Backend
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.api
        push: true
        tags: ${{ env.DOCKER_USER }}/mlops-backend:latest

    - name: Build and Push Frontend
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.st
        push: true
        tags: ${{ env.DOCKER_USER }}/mlops-frontend:latest